# <span style="color:green"><center>Diplomado en Inteligencia Artificial y Aprendizaje Profundo</center></span>

# <span style="color:red"><center>Introducción a Tensores en TensorFlow</center></span>

##   <span style="color:blue">Profesores</span>

1. Alvaro Mauricio Montenegro Díaz, ammontenegrod@unal.edu.co
2. Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com 
3. Campo Elías Pardo Turriago, cepardot@unal.edu.co 

##   <span style="color:blue">Asesora Medios y Marketing digital</span>
 

4. Maria del Pilar Montenegro, pmontenegro88@gmail.com 

## <span style="color:blue">Asistentes</span>

5. Oleg Jarma, ojarmam@unal.edu.co 
6. Laura Lizarazo, ljlizarazore@unal.edu.co
7. Julieth López, julalopezcas@unal.edu.co

## <span style="color:blue">Contenido</span> 

* [Importar librerías](#Importar-librerías)
* [Esenciales](#Esenciales)
* [Algebra mínima de tensores](#Algebra-mínima-de-tensores)
* [Funciones de Reducción](#Funciones-de-Reducción)
* [Tipo, forma y dimensión](#Tipo,-forma-y-dimensión)
* [Indexación](#Indexación)
    * [Indexación en un solo eje](#Indexación-en-un-solo-eje)
    * [Extracción de parte de un tensor: slices](#Extracción-de-parte-de-un-tensor:-slices)
    * [Indexación multi-eje](#Indexación-multi-eje)
* [Manipular formas](#Manipular-formas)
    * [Aplana un tensor](#Aplana-un-tensor)
    * [Definición Conversión de tipos. Cast](#Definición-Conversión-de-tipos.-Cast)
* [Radiofusión (broadcasting)](#Radiofusión-(broadcasting))
    * [tf.broadcast_to](#tf.broadcast-to)
    * [tf.convert_to_tensor](#tf.convert-to-tensor)
* [Tensores irregulares (ragged tensors)](#Tensores-irregulares-(ragged-tensors))
* [Tensores de strings](#Tensores-de-strings)
    * [string to number](#string-to-number)
* [Tensores dispersos. SparseTensor](#Tensores-dispersos.-SparseTensor)

## <span style="color:blue">Importar librerías</span> 

In [1]:
import tensorflow as tf
import numpy as np

2021-10-09 09:02:07.362265: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


## <span style="color:blue">Esenciales</span> 

In [2]:
t0 = tf.constant(4)
print(t0)

tf.Tensor(4, shape=(), dtype=int32)


2021-10-09 09:02:08.420280: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-10-09 09:02:08.421075: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-10-09 09:02:08.685874: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-09 09:02:08.686664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.2GHz coreCount: 30 deviceMemorySize: 5.79GiB deviceMemoryBandwidth: 312.97GiB/s
2021-10-09 09:02:08.686686: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-10-09 09:02:08.712539: I tensorflow/stream_executor/platform/defa

In [3]:
t1 = tf.constant([1, 3, 4])
print(t1)

tf.Tensor([1 3 4], shape=(3,), dtype=int32)


In [4]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
t235 = tf.constant([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
                    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]])
print(t235)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]], shape=(2, 3, 5), dtype=int32)


In [6]:
t235.numpy()

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)

In [7]:
t235.numpy().shape

(2, 3, 5)

In [8]:
t235.shape

TensorShape([2, 3, 5])

## <span style="color:blue">Algebra mínima de tensores</span> 

In [ ]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

print("a =",a,"\n")
print("b =",b,"\n")
print("tf.add(a,b) =",tf.add(a,b),"\n")
print("tf.multiply(a,b) =",tf.multiply(a,b),"\n")
print("tf.matmul(a,b) =",tf.matmul(a,b),"\n")

In [ ]:
print(a+b,"\n") #suma
print(a*b, "\n") #multiplicación directa
print(a@b, "\n") #multiplicación matricial

## <span style="color:blue">Funciones de Reducción</span> 

In [ ]:
c = tf.constant([[4.0, 5.0],[10.0,1.0]])

print(c,"\n")
print("maximo=",tf.reduce_max(c),"\n")
print("minimo=",tf.reduce_min(c),"\n")
print("mean=",tf.reduce_mean(c),"\n")
print("arg_max=",tf.argmax(c),"\n")
print("soft_max=",tf.nn.softmax(c),"\n")
print(tf.reduce_sum(tf.nn.softmax(c),axis=1),"\n")

## <span style="color:blue">Tipo, forma y dimensión</span>

In [ ]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(t.dtype,"\n")
print(t.shape,"\n")
print(t.shape[2],"\n")
print(t.ndim,"\n")
print(tf.size(t.numpy()),"\n") #porque se vuelve a poner .numpy()?

## <span style="color:blue">Indexación</span>

### Indexación en un solo eje

+ Los índices empiezam em cero.
+ Los índices negativos cuentan hacia atrás desde el final.
+ Los dos puntos (:) se utilizan para los cortes. inicio:final:salto

In [ ]:
t1 =  tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print("Primero: ", t1[0])
print("Segundo: ", t1[1])
print("Ultimo: ", t1[-1].numpy())

### Extracción de parte de un tensor: slices

In [ ]:
print('Todo', t1[:].numpy())
print('Antes la posición 4 ', t1[:4].numpy())
print('Desde la posición 4 hasta el final', t1[4:].numpy())
print('Desde la posición 4 hasta la anterior a 7', t1[4:7].numpy())
print('Todos los elementos en posición par ', t1[::2].numpy())
print('Invertido todo el orden', t1[::-1].numpy())

### Indexación multi-eje

In [ ]:
t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23.numpy())

In [ ]:
print('Posición 1,1 = ',t23[1,1].numpy())
print('Segunda fila: ', t23[1,:].numpy())
print('Segunda columna: ', t23[:,1].numpy())
print('Última columna: ', t23[:,-1].numpy())
print('Primer elemento de la última columna: ', t23[0,-1].numpy())
print('Saltarse la primera columna: \n', t23[:,1:].numpy())

In [ ]:
t = tf.constant([    
  [[0, 1, 2, 3, 4.8],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])  #flotantes
print(t.numpy())

In [ ]:
print('Extrae la primera capa\n', t[0,:,:],"\n")
print('Extrae la segunda capa\n', t[1])

## <span style="color:blue">Manipular formas</span>

In [ ]:
x = tf.constant([[1],[2],[3]])
print(x.shape)
print(x.shape.as_list())

In [ ]:
reshaped = tf.reshape(x,[1,3])
print(reshaped.numpy())
print(x.numpy())

Con *tf.reshape* los datos mantienen su disposición en la memoria y se crea un nuevo tensor, con la forma solicitada, apuntando a los mismos datos. TensorFlow usa un orden de memoria de "fila principal" de estilo C, donde incrementar el índice de la derecha corresponde a un solo paso en la memoria.

![tensor before](../Imagenes/tensor_before.png)

Tensor antes de reshape

<img src="../Imagenes/tensor_after.png" align="left" width="40%">
<img src="../Imagenes/tensor_after2.png" align="right" width="30%">

Tensores despues de reshape

### Aplana un tensor

Esta operación permite ver el orden como están organizados los datos en memoria.

In [ ]:
print("t actual: \n", t.numpy())
flat = tf.reshape(t, [-1])
print("\n t aplanado: \n", flat.numpy())

Normalmente, el único uso razonable de tf.reshape es combinar o dividir ejes adyacentes (o agregar / eliminar 1 s).

Para este tensor de 2x3x5, remodelar a (2x3)x5 o 2x (3x5) son dos cosas razonables, ya que los cortes no se mezclan:


In [ ]:
print(t.shape.as_list())

In [ ]:
print(tf.reshape(t, [2*3,5]))

In [ ]:
print(tf.reshape(t, [2,3*5]))

No es necesario definir todos tamaños en todas las dimensiones. veámos como rehacer los dos ejemplos ateriores, respecitivamente. El -1 le dice a tf que decida cuál es la dimensión correcta.

In [25]:
print(tf.reshape(t, [-1,5]))

tf.Tensor(
[[ 0.   1.   2.   3.   4.8]
 [ 5.   6.   7.   8.   9. ]
 [10.  11.  12.  13.  14. ]
 [15.  16.  17.  18.  19. ]
 [20.  21.  22.  23.  24. ]
 [25.  26.  27.  28.  29. ]], shape=(6, 5), dtype=float32)


In [26]:
print(tf.reshape(t, [3,-1]))

tf.Tensor(
[[ 0.   1.   2.   3.   4.8  5.   6.   7.   8.   9. ]
 [10.  11.  12.  13.  14.  15.  16.  17.  18.  19. ]
 [20.  21.  22.  23.  24.  25.  26.  27.  28.  29. ]], shape=(3, 10), dtype=float32)


Aunque es posible hacer el siguiente reshape no tiene sentido, porque se pierde la integridad de la información. 

Asegúrese que entiende la razón.

In [27]:
print(tf.reshape(t, [3,2,5]))

tf.Tensor(
[[[ 0.   1.   2.   3.   4.8]
  [ 5.   6.   7.   8.   9. ]]

 [[10.  11.  12.  13.  14. ]
  [15.  16.  17.  18.  19. ]]

 [[20.  21.  22.  23.  24. ]
  [25.  26.  27.  28.  29. ]]], shape=(3, 2, 5), dtype=float32)


### Definición Conversión de tipos. Cast

In [28]:
f64_tensor = tf.constant([2.0, 4.0, 6.0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16) #solo llega a 16 decimales
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
tf.Tensor([2 4 6], shape=(3,), dtype=uint8)


## <span style="color:blue">Radiofusión (broadcasting)</span>

La radiodifusión es un concepto tomado de la función equivalente en NumPy . En resumen, bajo ciertas condiciones, los tensores más pequeños se "estiran" automáticamente para adaptarse a tensores más grandes cuando se ejecutan operaciones combinadas en ellos.

El caso más simple y común es cuando intenta multiplicar o agregar un tensor a un escalar. En ese caso, el escalar se transmite para que tenga la misma forma que el otro argumento.

In [29]:
x = tf.constant([1, 2 ,3])
y = tf.constant(2)
z = tf.constant([2, 2 ,2])

# el mismo resultado
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [30]:
x = tf.reshape(x, [3,1])
y = tf.range(1,5)
print(x, "\n")
print(y, "\n")

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 



In [31]:
print(tf.multiply(x,y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Del mismo modo, los ejes con longitud 1 se pueden estirar para que coincidan con los otros argumentos. Ambos argumentos se pueden estirar en el mismo cálculo.

En este caso, una matriz de 3x1 se multiplica por elementos por una matriz de 1x4 para producir una matriz de 3x4. Observe que el 1 inicial es opcional: la forma de y es [4]. En matemáticas esta multiplicación se conoce como producto externo.

### tf.broadcast_to

In [32]:
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [33]:
print(tf.broadcast_to([[1],[2],[3]], [3,3]))

tf.Tensor(
[[1 1 1]
 [2 2 2]
 [3 3 3]], shape=(3, 3), dtype=int32)


### tf.convert_to_tensor

La mayoría de las operaciones, como *tf.matmul* y *tf.reshape* toman argumentos de la clase *tf.Tensor*. Sin embargo, notará que en el caso anterior, se aceptan objetos de Python con forma de tensores.

La mayoría, pero no todas, las operaciones llaman a *tf.convert_to_tensor* con argumentos no tensoriales. Existe un registro de conversiones, y la mayoría de las clases de objetos como *ndarray* , *TensorShape* , de Python, y *tf.Variable* se convertirán todas automáticamente.



## <span style="color:blue">Tensores irregulares (ragged tensors) </span>

Un tensor con números variables de elementos a lo largo de algún eje se llama "irregular". Utilice tf.ragged.RaggedTensor para datos irregulares.

Por ejemplo, esto no se puede representar como un tensor regular:



![ragged](../Imagenes/ragged.png)

In [34]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [35]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
     print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


En su lugar, cree un *tf.RaggedTensor* usando *tf.ragged.constant* :

In [36]:
ragged_t = tf.ragged.constant(ragged_list)

print(ragged_t.shape)

(4, None)


## <span style="color:blue">Tensores de strings</span>

In [37]:
st = tf.constant("Este tensor string")
print(st)

tf.Tensor(b'Este tensor string', shape=(), dtype=string)


In [38]:
st = tf.constant(["Este tensor string",
                 "Cadena 2",
                 "Cadena 3",
                 "🥳"])
print(st)

tf.Tensor([b'Este tensor string' b'Cadena 2' b'Cadena 3' b'\xf0\x9f\xa5\xb3'], shape=(4,), dtype=string)


El prefijo b indica que el tipo (dtype)  tf.string no es unicode (estandar de codificación de caracteres).

In [39]:
print(tf.strings.split(st))

<tf.RaggedTensor [[b'Este', b'tensor', b'string'], [b'Cadena', b'2'], [b'Cadena', b'3'], [b'\xf0\x9f\xa5\xb3']]>


In [40]:
st_split = tf.strings.split(st)
for i in st_split:
    print(i)

tf.Tensor([b'Este' b'tensor' b'string'], shape=(3,), dtype=string)
tf.Tensor([b'Cadena' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Cadena' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'\xf0\x9f\xa5\xb3'], shape=(1,), dtype=string)


### String to number

In [41]:
st = tf.constant("1 10 10.4")

print(tf.strings.to_number(tf.strings.split(st, " ")))

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


## <span style="color:blue">Tensores dispersos. SparseTensor</span>

In [42]:
# tensor disperso
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape =[3,4])
print(sparse_tensor, "\n")

# convierte a tensor denso
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
