<figure>
<img src="../Imagenes/logo-final-ap.png"  width="80" height="80" align="left"/> 
</figure>

# <span style="color:blue"><left>Aprendizaje Profundo</left></span>

# <span style="color:red"><center>Pytorch</center></span>

<center>Tensores</center>

<figure>
<center>
<img src="../Imagenes/Pytorch_logo.png" width="400" height="400" align="center"/>
</center>
</figure>


Fuente [OpenAI Gym](https://gym.openai.com/)

##   <span style="color:blue">Autores</span>

1. Alvaro Mauricio Montenegro Díaz, ammontenegrod@unal.edu.co
2. Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com 

##   <span style="color:blue">Diseño gráfico y Marketing digital</span>
 

1. Maria del Pilar Montenegro Reyes, pmontenegro88@gmail.com 

## <span style="color:blue">Referencias</span> 

1. Basado en los [tutoriales de Pytorch](https://pytorch.org/tutorials/)
1. [Deep learning for coders with FastAI and Pytorch](http://library.lol/main/F13E85845AE48D9FD7488FE7630A9FD3)

## <span style="color:blue">Contenido</span>

* [Introducción](#Introducción)
* [Importa Torch](#Importa-Torch)
* [Inicializa un Tensor](#Inicializa-un-Tensor)
* [Operaciones sobre Tensores](#Operaciones-sobre-Tensores)
* [Grafo de cálculo dinámico y retropropagación(backpropagation)](#Grafo-de-cálculo-dinámico-y-retropropagación(backpropagation))
* [Soporte para GPU](#Soporte-para-GPU)

## <span style="color:blue">Introducción</span>

Los tensores son similares a los ndarrays de `NumPy`, excepto que los tensores pueden ejecutarse en GPU u otros aceleradores de hardware. De hecho, los tensores y las matrices NumPy a menudo pueden compartir la misma memoria subyacente, lo que elimina la necesidad de copiar datos (consulte [Puente con NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)). Los tensores también están optimizados para la diferenciación automática.

## <span style="color:blue">Importa Torch</span>

In [3]:
import torch
import numpy as np

In [2]:
print("Using torch", torch.__version__)

Using torch 1.10.2


## <span style="color:blue">Inicializa un Tensor</span>

### Directamente de los datos

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

### A partir de arreglos Numpy

In [5]:
np_array = np.array(data)

x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

Desde otro tensor

In [8]:
# semilla para reproductibilidad
torch.manual_seed(100)

x_ones = torch.ones_like(x_data) # retiene las propiedades de x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)# sobre escribe le tipo de dato
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]]) 



### Con valores aleatorios y constantes

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape) # Uniform[0,1]
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## <span style="color:blue">Operaciones sobre Tensores</span>

### Indexación y rebanado(slicing) al estilo  numpy

In [12]:
tensor = torch.ones(4, 4)
print('Primera fila: ', tensor[0])
print('Primera  columna: ', tensor[:,0])
print('Ultima columna: ', tensor[...,-1])
tensor[:,1] = 0
print(tensor)

Primera fila:  tensor([1., 1., 1., 1.])
Primera  columna:  tensor([1., 1., 1., 1.])
Ultima columna:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenación de tensores

In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Operaciones aritméticas

In [13]:
# Multiplicación matricial
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# Multiplicación elemento a elemento
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Agregación

In [16]:
agg = tensor.sum()
agg_item = agg.item()
print('agg = ', agg)
print('agg_item = ', agg_item)
print('type(gg_item):', type(agg_item))

agg =  tensor(12.)
agg_item =  12.0
type(gg_item): <class 'float'>


### Operaciones in place

In [17]:
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Puente con Numpy

In [18]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

# el cambio se refleja en el arreglo numpy
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### Cambio de forma de los tensores

In [19]:
x = torch.arange(6)
print('x:', x)

x: tensor([0, 1, 2, 3, 4, 5])


In [20]:
x.view(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [22]:
# aplanando 4 imágenes

batch_size = 4
n_rows = 2
n_columns = 2
x = torch.rand(batch_size, n_rows, n_columns)
print(x)

tensor([[[0.5557, 0.9770],
         [0.4440, 0.9478]],

        [[0.7445, 0.4892],
         [0.2426, 0.7003]],

        [[0.5277, 0.2472],
         [0.7909, 0.4235]],

        [[0.0169, 0.2209],
         [0.9535, 0.7064]]])


In [25]:
x = x.view(batch_size, n_rows*n_columns)
print(x)

tensor([[0.5557, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909, 0.4235],
        [0.0169, 0.2209, 0.9535, 0.7064]])


In [26]:
x = x.permute(1,0)
print(x)

tensor([[0.5557, 0.7445, 0.5277, 0.0169],
        [0.9770, 0.4892, 0.2472, 0.2209],
        [0.4440, 0.2426, 0.7909, 0.9535],
        [0.9478, 0.7003, 0.4235, 0.7064]])


## <span style="color:blue">Grafo de cálculo dinámico y retropropagación(backpropagation)</span>

Una de las principales razones para usar PyTorch en proyectos de aprendizaje profundo es que `podemos obtener automáticamente gradientes/derivados de las funciones` que definamos. Principalmente usaremos PyTorch para implementar redes neuronales, y ellas son solamente funciones sofisticadas. Si usamos matrices de peso en nuestra función que queremos aprender, entonces se llaman parámetros o simplemente pesos.

Si nuestra red neuronal generara un solo valor escalar, hablaríamos de tomar la derivada, pero verá que con bastante frecuencia tendremos múltiples variables de salida ("valores"); en ese caso hablamos de gradientes. Es un término más general.

Dada una entrada $\mathbf{x}$, definimos nuestra función manipulando esa entrada, generalmente mediante multiplicaciones de matrices con matrices de peso(weight) y sumas con los llamados vectores de sesgo(bias). A medida que manipulamos nuestra entrada, estamos creando automáticamente un grafo computacional. Este grafo muestra cómo llegar a nuestra salida a partir de nuestra entrada. 

PyTorch es un marco definido por ejecución; esto significa que podemos simplemente hacer nuestras manipulaciones, y PyTorch hará un seguimiento de ese grafo por nosotros. Por lo tanto, creamos un grafo de cálculo dinámico en el camino.

### Ejemplo

Primero creamos un ejemplo de tensor simple y luego le agregaremos el grafo de cálculo dinámico. 

In [29]:
x = torch.ones((3,))
print(x.requires_grad)

False


In [33]:
x.requires_grad = True
print(x.requires_grad)

True


Vamos a crear la siguiente función
$$
y = \frac{1}{|x|} \sum_i [(x_i+2)^2 + 3],
$$

para luego calcular su gradiente $\frac{\partial y}{\partial x}$ enel punto $[1, 2, 3]$. En la expresión, $|x|$ será el tamaño(forma) de $x$.


In [34]:
x = torch.arange(3, dtype=torch.float32, requires_grad=True) # solamente puede usar floats para calcular gradientes
print('x: ', x)

x:  tensor([0., 1., 2.], requires_grad=True)


In [ ]:
Ahora construimos el grafo de la función

In [35]:
a = x + 2
b = a**2
c = b + 3
y = c.mean()
print('y = ', y)


y =  tensor(12.6667, grad_fn=<MeanBackward0>)


#### Cálculo del gradiente

In [36]:
y.backward()

*x.grad()* contiene el gradiente $\frac{\partial y}{\partial x}$ en el punto $x = [1, 2, 3]$

In [38]:
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])


El cálculo se realizó de la siguiente forma

$$
\frac{\partial y}{\partial x_i} = \frac{\partial y}{\partial c_i} \frac{\partial c_i}{\partial b_i} \frac{\partial b_i}{\partial a_i} \frac{\partial a_i}{\partial x_i} 
$$

$$
\frac{\partial a_i}{\partial x_i} = 1, \quad \frac{\partial b_i}{\partial a_i} = 2\cdot a_i \quad \frac{\partial c_i}{\partial b_i} = 1,\quad \frac{\partial y}{\partial c_i} = \frac{1}{3}
$$

Entonces, si $x = [1, 2, 3]$ se obtiene $\frac{\partial y}{\partial x} = [4/3, 2, 8/3]$.

## <span style="color:blue">Soporte para GPU</span>

In [40]:
gpu_avail = torch.cuda.is_available()
print(f"¿Hay  GPU disponible? {gpu_avail}")

¿Hay  GPU disponible? False


In [41]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Device cpu


In [42]:
x = torch.zeros(2, 3)
x = x.to(device)
print("X", x)

X tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [43]:
x.device

device(type='cpu')