# <span style="color:green"><center>Diplomado en Inteligencia Artificial y Aprendizaje Profundo</center></span>

# <span style="color:red"><center>Taller de numpy </center></span>

## <span style="color:blue">Autores</span>

1. Oleg Jarma, ojarmam@unal.edu.co
2. Julieth López, julalopezcas@unal.edu.co

##   <span style="color:blue">Profesores</span>

2. Alvaro Mauricio Montenegro Díaz, ammontenegrod@unal.edu.co
3. Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com 
4. Campo Elías Pardo Turriago, cepardot@unal.edu.co 

##   <span style="color:blue">Asesora Medios y Marketing digital</span>

5. Maria del Pilar Montenegro, pmontenegro88@gmail.com 

## Contenido

* [¿Qué es?](#¿Qué-es?)
    * [¿Por qué usar arrays de numpy y no listas o tuplas de python?](#¿Por-qué-usar-arrays-de-numpy-y-no-listas-o-tuplas-de-python?)
* [Creación básica de arrays](#Creación-básica-de-arrays)
* [Indexación básica](#Indexación-básica)
* [Diferentes tipos de datos en el los arrays](#Diferentes-tipos-de-datos-en-los-arrays)
* [Forma de los arrays](#Forma-de-los-arrays)
    * [Reformar arrays](#Reformar-arrays)
    * [Dimensión desconocida](#Dimensión-desconocida)
    * [Transpuesta](#Transpuesta)
* [Iterar arrays](#Iterar-arrays)
* [Aplicar operaciones entre arrays](#Aplicar-operaciones-entre-arrays)
    * [Suma](#Suma)
    * [Multiplicación](#Multiplicación)
    * [Multiplicación matricial](#Multiplicación-matricial)

## ¿Qué es?

Numpy es un paquete de python dedicado principalmente al manejo de conjuntos o "arrays". Extendiendose luego al álgebra lineal, matrices y probabilidad.

### ¿Por qué usar arrays de numpy y no listas o tuplas de python?

Aunque python base tiene listas, el usar arrays es más rápido y consume menos memoria. Algo altamente necesario cuando se hacen operaciones de gran tamaño como puede ser el algebra matricial, por ejemplo.

In [1]:
import numpy as np

## Creación básica de arrays

Vamos a crear arrays de distintas dimensiones. Para esto podemos usar números, listas o tuplas.

In [2]:
a=np.array(13) #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")

a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



Para revisar el número de dimensiones, usamos `ndim`

In [3]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Indexación básica

El proceso de indexación en numpy es similar al de las listas en python. Cada número implica buscar la posición en cada dimensión del array

In [4]:
print("a =",a)
print("b[2] = ",b[2])
print("c[1] =",c[1])
print("d[1] =",d[1])

a = 13
b[2] =  3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


In [5]:
print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2])
print("d[1,0,2] =",d[1,0,2])

a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


Similarmente podemos segmentar **arrays** como en el las listas de python,

In [6]:
print(b[1:4]) #b = [1 2 3 4] 
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[2 3 4]
[6 7]


## Diferentes tipos de datos en los arrays

Los arrays no están limitados a números enteros, pueden también tener cadenas, booleanos, o de punto flotante.

In [7]:
frutas = np.array(['Manzana', 'Naranja', 'Uva']) #cadenas
print(frutas.dtype)

<U7


Podemos manipular el tipo de los datos del array dentro de la función de creación del array `np.array`, siempre y cuando el cambio sea posible. Por ejemplo podemos pasar enteros a cadenas (integers a strings) pero no viceversa.

In [8]:
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


In [9]:
try:
    error_array = np.array(['a', '2', '3'], dtype='i')
except:
    print("hay un error en su lógica")

hay un error en su lógica


Podemos también cambiar el tipo en arrays ya existentes

In [10]:
floating_array = np.array([1.1, 2.1, 3.1]) #punto flotante

int_array = floating_array.astype('i')
print(int_array)

[1 2 3]


## Forma de los arrays

La forma es distinta a la dimensión. Esta se define como el número de elementos de la dimensión. 

In [11]:
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


### Reformar arrays

Podemos cambiar la forma de los arrays. Esto significa aumentar el número de dimensiones o cambiar cuantos elementos hay por dimensión.

In [12]:
print("c =",c,"\n")
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



¿Podemos hacer cualquier cambio en la forma? Si, mientras las que se quieren conseguir coincidan con la cantidad de elementos.

In [13]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


`d` es un array con 16 elementos, así que podemos hacer reshape con tamaños por ejemplo 1x16, 4x4, 8x2, 2x4x2 Por ejemplo, no podemos reformar un arrey a 3x5.

In [14]:
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones')

Hay un error en sus operaciones


In [15]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

### Dimensión desconocida

Podemos definir el cambio de forma con una dimensión la cual no sabemos el tamaño. Numpy se encargará de definir el tamaño que mejor se ajuste.

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos usar la dimensión desconocida para "aplanar" el array a una dimensión.

In [17]:
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Transpuesta

Para transponer el array utilizamos `.T`

In [18]:
print("c =",c,"\n")
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Iterar arrays

Podemos usar los métodos tradicionales para iterar.

In [19]:
for x in d:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


Si queremos iterar cada elemento, necesitamos un `for` por cada dimensión

In [20]:
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


Esto por supuesto no es óptimo. Así que numpy tiene la función `nditer()` para estos casos.

In [21]:
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


## Aplicar operaciones entre arrays

*numpy* tiene sus propias formas de aplicar operaciones:

### Suma

*numpy* tiene dos funciones, `np.add()` y `np.sum()`. El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma

In [22]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [23]:
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


Si aplicamos un eje en `np.sum()`, se aplica la suma en ese mismo eje. Por ejemplo, con eje 0, se obtienen los mismos resultados que `np.add()`

In [24]:
np.sum([arr1,arr2, arr3],axis=0)

array([[8, 8, 8],
       [8, 8, 8]])

In [25]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

### Multiplicación

El primer caso de multiplicación es `np.prod()`, que funciona similar que `np.sum()`

In [26]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


### Multiplicación Matricial

Para la multiplicación de matrices usamos `np.matmul()` o `np.dot()`. hay que tener en cuenta la forma de las matrices

In [27]:
np.matmul(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

In [28]:
np.dot(arr1, arr2.T)

array([[28, 10],
       [73, 28]])

Se comportan distinto con matrices de dos dimensiones, para otros casos hacen cosas distintas

In [29]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [30]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



Con *matmul* no se pueden multiplicar escalares **c.A** (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con *dot*, donde este toma los números dentro de las matrices como elementos.

In [31]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])