# <span style="color:green"><center>Diplomado en Inteligencia Artificial y Aprendizaje Profundo</center></span>

# <span style="color:red"><center>Taller introductorio al ambiente R</center></span>

##   <span style="color:blue">Profesores</span>

- Alvaro Mauricio Montenegro Díaz, ammontenegrod@unal.edu.co
- Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com 
- Campo Elías Pardo Turriago, cepardot@unal.edu.co 
- Oleg Jarma, ojarmam@unal.edu.co 

##   <span style="color:blue">Asesora Medios y Marketing digital</span>

- Maria del Pilar Montenegro, pmontenegro88@gmail.com 

##   <span style="color:blue">Introducción</span>

Inspirado en el [Manual de CRAN](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)

R es un ambiente de software especializado en la manipulación de datos, el cálculo matemático y el desarrollo de gráficas. Entre sus ventajas están las siguientes:

- Capacidad de manipular y guardar grandes cantidades de datos
- Un conjunto de operadores para calculo entre vectores y, principalmente, matrices
- Una enorme colección de herramientas para el análisis de datos.
- habilidades de despliegue de gráficos para representación de datos
- Un lenguaje de programación "S". Simple y efectivo, que incluye condicionales, ciclos, funciones recursivas y capacidades de entrada y salida.

R es usado principalmente un sistema de programación de estadística, debido a su desarrollo de gráficas y sus múltiples paquetes dedicados a la aplicaciones de metodologías.

R(O mejor dicho S) es un lenguaje interpretado, lo cual lo hace fácil de comprender si ya se tienen conocimientos de Python.



##   <span style="color:blue">Creación básica de variables</span>

la creación de variables es similar a Python, no es necesario decir el tipo de dato que será este. Para definir la variable usamos el símbolo `<-`(`=` sigue siendo válido pero no siempre se recomienda).

Se pueden guardar los mismos tipos de datos que en Python, pero con diferentes nombres

In [11]:
nombre <- "David" #variable tipo "character", o string
edad <- 39 #variable tipo "numeric" o número genérico
litros <- 1000L #variable "integer". o entero 
complejo <- 3i + 1 #variable "complex"
logico <- TRUE #variable "logical" o booleano

class(nombre)
class(edad)
class(litros)
class(complejo)
class(logico)

[1] "character"

[1] "numeric"

[1] "integer"

[1] "complex"

[1] "logical"

la función `print()` también es válida en R y es necesaria en ciertos aspectos.

In [12]:
print(litros)
print(edad)
print(complejo)

[1] 1000
[1] 39
[1] 1+3i


Es posible hacer la conversión a los diferentes tipos de números que tenemos

In [13]:
as.integer(edad)
as.complex(litros)
as.numeric(complejo)

[1] 39

[1] 1000+0i

Warning message in eval(expr, envir, enclos):
“imaginary parts discarded in coercion”


[1] 1

Y por supuesto, podemos pasar a caracter. También podemos pasar de caracter a número siempre y cuando tenga un equivalente

In [14]:
complejo_char <- as.character(complejo)
print(complejo_char)

as.complex(complejo_char)
as.numeric(nombre)


[1] "1+3i"


[1] 1+3i

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”


[1] NA

##   <span style="color:blue">Operaciones numéricas básicas</span>

Por supuesto, R es capaz de hacer una gran cantidad de operaciones comunes

In [15]:
10 + 5 #Suma

10 - 5 #Resta

3 * 3 #Multiplicación

15 / 5 #División

3 ^ 2 #Exponente

4 %% 3 #Modulo

14 %/% 5 #División sin decimal

[1] 15

[1] 5

[1] 9

[1] 3

[1] 9

[1] 1

[1] 2

Estas no son las únicas funciones en el paquete base. Encontramos también las siguientes funciones útiles:

In [16]:
max(5, 10, 15) #Valor máximo

min(5, 10, 15) #Valor mínimo

sqrt(25) #Raíz cuadrada

abs(-5.5) #Valor absoluto

ceiling(1.4) #Función techo

floor(1.4) #función piso

[1] 15

[1] 5

[1] 5

[1] 5.5

[1] 2

[1] 1

##   <span style="color:blue">Ciclos</span>

###   <span style="color:blue">ciclos If y condicionales</span>

R hace uso de las condiciones lógicas matemáticas que ya conocemos. Podemos observar sus usos junto con los ciclos If, los cuales también están completamente implementados.

In [17]:
a <- 30

b <- 5

if(a>b){
    print("a es mayor que b")
}

[1] "a es mayor que b"


Podemos extender esto con un If Else y un else

In [18]:

if(a>b){
    print("a es mayor que b")
}else if (a == b){
    print("a es igual a b")
}else{
    print("b es mayor que a")
}

[1] "a es mayor que b"


Por supuesto podemos anidar estos ciclos

In [19]:
x <- 50

if(x > 10){
    print("mayor a 10")
    if(x > 50){
        print("mayor a 50")
    }else{
        print("pero no mayor a 50")
    }
}else {
   print("menor o igual a 10")
}

[1] "mayor a 10"
[1] "pero no mayor a 50"


Y podemos usar operadores lógicos para tener varias condiciones

In [20]:
a <- 200
b <- 33
c <- 500

if (a > b & c > a){
  print("Ambas condiciones son verdaderas")
}else {
   print("Al menos una condición no es verdadera")
}

[1] "Ambas condiciones son verdaderas"


In [21]:
if (a > b | c > a){
  print("Al menos una condición es verdadera")
}else {
   print("Ninguna condición es verdadera")
}

[1] "Al menos una condición es verdadera"


###   <span style="color:blue">Ciclos While</span>

Usamos el ciclo while para ejecutar código siempre y cuando se mantenga una condición.

In [22]:
i <- 1

while (i < 6){
    print(i)
    i <- i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


Existe el `break`, que permite detener el ciclo 

In [23]:
i <- 1
while (i < 6){
    print(i)
    i <- i + 1
    if (i==4){
        break
    }
}

[1] 1
[1] 2
[1] 3


También podemos usar `next`, para saltar una iteración del ciclo sin detenerlo completamente, pero hay que ser conscientes de la naturaleza interpretada de R

In [24]:
i <- 0
while (i < 6){
    i <- i + 1
    if (i == 3){
        next
    }
    print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5
[1] 6


###   <span style="color:blue">Ciclos for</span>

Podemos usar for para iterar sobre secuencias. `break` y `next` también son aplicables aquí

In [25]:
for (x in 0:10){
    if (x == 3){
        next
    }else if(x == 8) {
        break
    }
    print(x)
}

[1] 0
[1] 1
[1] 2
[1] 4
[1] 5
[1] 6
[1] 7


##   <span style="color:blue">Creación de funciones</span>

Podemos definir nuestras propias funciones en R.

In [26]:
my_function <- function(){
    print("Hola Mundo!")
}

Ahora simplemente llamamos la función y se aplican los métodos que le definimos

In [27]:
my_function()

[1] "Hola Mundo!"


Ahora podemos definir los argumentos que vamos a pasar dentro de la función. Estos tienen que ser el número correcto que se van a usar.

In [28]:
my_function <- function(nombre, apellido){
    paste(nombre, apellido)
}

my_function("Pedro", "Picapiedra")

[1] "Pedro Picapiedra"

Podemos definir un valor predeterminado a los argumentos

In [29]:
my_function <- function(nombre, apellido = ""){
    paste("Hola, soy", nombre, apellido)
}

my_function("Pedro")

[1] "Hola, soy Pedro "

Si queremos que la función retorne un resultado, se utiliza `return()` al final de esta

In [30]:
mult_cinco <- function(x = 1){
    return (5 * x)
}

print(mult_cinco(2))
print(mult_cinco(6))

[1] 10
[1] 30


##   <span style="color:blue">Estructuras de datos</span>

###   <span style="color:blue">Vectores</span>

Para el contexto de R, un vector es un conjunto unidimensional de elementos que comparten un mismo tipo

Creamos un vector usando `c()` y agregando los elementos, separandolos por coma

In [31]:
# Vector de caracteres

frutas <- c("Banana", "Manzana", "Guanabana")

frutas

[1] "Banana"    "Manzana"   "Guanabana"

Podemos obtener la cantidad de datos en un vector usando `length()`

In [32]:
length(frutas)

[1] 3

En el caso de números, particularmente enteros, podemos definirlos de la forma normal o, si queremos una secuencia, usamos el operador `:`

In [33]:
# Vector numérico

numeros <- c(1, 2, 3)

numeros

numeros_seq <- 1:5

numeros_seq

[1] 1 2 3

[1] 1 2 3 4 5

Es posible hacer secuencias con números decimales, pero hay que tomar en cuenta que la distancia entre elementos es siempre 1.

In [34]:
decimales1 <- 1.5:6.5
decimales1

decimales2 <- 1.5:6.3
decimales2

[1] 1.5 2.5 3.5 4.5 5.5 6.5

[1] 1.5 2.5 3.5 4.5 5.5

Si queremos distancias más grandes (o más pequeñas) usamos la función `sequ()`


In [35]:
secuencia1 <- seq(from = 0, to = 100, by = 20)
secuencia1

secuencia2 <- seq(from = 0.3, to = 5, by = 0.5)
secuencia2

[1]   0  20  40  60  80 100

[1] 0.3 0.8 1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8

Es posible acceder a los elementos de los vector usando sus indices. Cabe avisar que el primer elemento tiene indice `[1]`

In [36]:
frutas[1]

[1] "Banana"

También podemos acceder a varios elementos a la vez usando un vector como indice

In [37]:
frutas <- c("Banana", "Manzana", "Guanabana", "Maracuyá", "Zapote", "Mamoncillo")

frutas[c(1,3)]

[1] "Banana"    "Guanabana"

O definiendo una secuencia

In [38]:
frutas[1:3]

[1] "Banana"    "Manzana"   "Guanabana"

O las dos cosas a la vez

In [39]:
frutas[c(1,3:5)]

[1] "Banana"    "Guanabana" "Maracuyá"  "Zapote"

Podemos usar índices negativos, pero esto significa que se accederán a los elementos EXCEPTO los que tengan índice negativo.

In [40]:
frutas[c(-1,-3)]

[1] "Manzana"    "Maracuyá"   "Zapote"     "Mamoncillo"

Podemos también cambiar elementos del vector a partir de sus índices

In [41]:
frutas[1] <- "Pera"

frutas

[1] "Pera"       "Manzana"    "Guanabana"  "Maracuyá"   "Zapote"    
[6] "Mamoncillo"

###   <span style="color:blue">Listas</span>

Las listas son los equivalentes a las tuplas en Python. Estas pueden contener diferentes tipos de datos en uno mismo. Estos están ordenados y se pueden cambiar.

In [42]:
lista <- list("uno", 2, 7.5, TRUE)

lista

[[1]]
[1] "uno"

[[2]]
[1] 2

[[3]]
[1] 7.5

[[4]]
[1] TRUE

Podemos acceder a los elementos de la misma forma que lo hacemos con vectores

In [43]:
lista[2]
lista[c(1,3)]
lista[2:3]

[[1]]
[1] 2

[[1]]
[1] "uno"

[[2]]
[1] 7.5

[[1]]
[1] 2

[[2]]
[1] 7.5

Podemos revisar si un elemento específico está en la lista usando el operador `%in%`. Hay que tomar en cuenta que esta busqueda es sensible a mayusculas

In [50]:
frutas_lista <- list("Manzana", "Banana", "Cereza")

"Manzana" %in% frutas_lista

"manzana" %in% frutas_lista

[1] TRUE

[1] FALSE

Agregamos un nuevo elemento a la lista usando `append()`


In [45]:
append(frutas_lista, "Melocoton")

[[1]]
[1] "Manzana"

[[2]]
[1] "Banana"

[[3]]
[1] "Cereza"

[[4]]
[1] "Melocoton"

Podemos decir después de qué indice agregar el elemento

In [51]:
frutas_lista <- append(frutas_lista, "Melocoton", after = 2)
frutas_lista

[[1]]
[1] "Manzana"

[[2]]
[1] "Banana"

[[3]]
[1] "Melocoton"

[[4]]
[1] "Cereza"

###   <span style="color:blue">Iterando sobre estructuras</span>

Es posible pasar vectores y listas en un ciclo for. Iteraremos sobre los elementos de estas.

In [47]:
for (i in secuencia2){
    print(i)
}

[1] 0.3
[1] 0.8
[1] 1.3
[1] 1.8
[1] 2.3
[1] 2.8
[1] 3.3
[1] 3.8
[1] 4.3
[1] 4.8


In [52]:
for (fruta in frutas_lista){
    if(fruta == "Melocoton"){
        next
    }
    print(fruta)
}

[1] "Manzana"
[1] "Banana"
[1] "Cereza"


Podemos concatenar dos listas agregandolas en un único vector. Seguirán funcionando como listas

In [54]:
lista_num <- list(1, 2, 3)

lista_char <- list("a", "b")

lista_bool <- list(TRUE, TRUE, FALSE, TRUE)

lista_full <- c(lista_num, lista_char, lista_bool)

lista_full

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "a"

[[5]]
[1] "b"

[[6]]
[1] TRUE

[[7]]
[1] TRUE

[[8]]
[1] FALSE

[[9]]
[1] TRUE

###   <span style="color:blue">Matrices</span>

Las matrices son estructuras bidimensionales de datos que trabajan con columnas (vertical) y filas (horizontal).

Se usa la función `matrix()` para crear una de estas. Hay que especificar los parámetros `nrow` y `ncol`.

In [55]:
matriz1 <- matrix(c(1,2,3,4), nrow = 2, ncol = 2)
matriz1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

como se puede apreciar, esta crea primero las columnas. Para que el orden sea con respecto a filas, hay que agregar el parámetro `byrow=TRUE`

In [63]:
matriz1 <- matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE)
matriz1

[,1] [,2]
[1,] 1    2   
[2,] 3    4

Las matrices no tienen que ser numéricas, 

In [65]:
matriz_char <- matrix(c("a", "ab", "abc", "b", "bc", 6), nrow = 3, ncol = 2)
matriz_char

[,1] [,2]
[1,] a    b   
[2,] ab   bc  
[3,] abc  6

[1] "6"

Accedemos a los elementos individuales de las matrices de la forma `[x,x]`, donde el primer elemento es la posición en filas y el segundo en columnas.

In [66]:
matriz_char[3,2]

[1] "6"

podemos acceder a una fila(o columna) completa si no especificamos número en el eje que no necesitamos


In [67]:
matriz_char[3,]
matriz_char[,2]

[1] "abc" "6"

[1] "b"  "bc" "6"

Y podemos usar vectores para acceder a varios elementos

In [68]:
matriz_char <- matrix(c("a", "ab", "abc", "b", "bc", "bcd", "c", "cd", "cde"), nrow = 3, ncol = 3)
matriz_char[c(1,3),]
matriz_char[,c(1,3)]
matriz_char[c(1,3), c(1,3)]

[,1] [,2] [,3]
[1,] a    b    c   
[2,] abc  bcd  cde

[,1] [,2]
[1,] a    c   
[2,] ab   cd  
[3,] abc  cde

[,1] [,2]
[1,] a    c   
[2,] abc  cde

Agregamos nuevas filas y columnas con las funciones `rbdind()` y `cbind()`

In [71]:
matriz_char <- rbind(matriz_char, c("abcd", "bcde", "cdef"))
matriz_char

In [73]:
matriz_char <- cbind(matriz_char, c("d", "de", "def", "defg"))
matriz_char

[,1] [,2] [,3] [,4]
[1,] a    b    c    d   
[2,] ab   bc   cd   de  
[3,] abc  bcd  cde  def 
[4,] abcd bcde cdef defg