# <span style="color:green"><center>Aprendizaje Profundo</center></span>

# <span style="color:red"><center>Transformers- Modelos</center></span>

<center>Modelos HuggingFace</center>

##   <span style="color:blue">Autores</span>

1. Alvaro Mauricio Montenegro Díaz, ammontenegrod@unal.edu.co
2. Daniel Mauricio Montenegro Reyes, dextronomo@gmail.com 

##   <span style="color:blue">Diseño gráfico y Marketing digital</span>
 

1. Maria del Pilar Montenegro Reyes, pmontenegro88@gmail.com 

## <span style="color:blue">Asistentes</span>

## <span style="color:blue">Referencias</span> 

1. [HuggingFace. Transformers ](https://huggingface.co/transformers/)
1. [HuggingFace. Models](https://huggingface.co/course/chapter2/3?fw=tf)
1. [Tutorial Transformer de Google](https://www.tensorflow.org/text/tutorials/transformer)
1. [Transformer-chatbot-tutorial-with-tensorflow-2](https://blog.tensorflow.org/2019/05/transformer-chatbot-tutorial-with-tensorflow-2.html) 
1. [Transformer Architecture: The positional encoding](https://kazemnejad.com/blog/transformer_architecture_positional_encoding/)
1. [Illustrated Auto-attención](https://towardsdatascience.com/illustrated-self-attention-2d627e33b20a)
1. [Illustrated Attention](https://towardsdatascience.com/attn-illustrated-attention-5ec4ad276ee3#0458)
1. [Neural Machine Translation by Jointly Learning to Align and Translate (Bahdanau et. al, 2015)](https://arxiv.org/pdf/1409.0473.pdf)
1. [Effective Approaches to Attention-based Neural Machine Translation (Luong et. al, 2015)](https://arxiv.org/pdf/1508.04025.pdf)
1. [Attention Is All You Need (Vaswani et. al, 2017)](https://arxiv.org/pdf/1706.03762.pdf)
1. [Self-Attention GAN (Zhang et. al, 2018)](https://arxiv.org/pdf/1805.08318.pdf)
1. [Sequence to Sequence Learning with Neural Networks (Sutskever et. al, 2014)](https://arxiv.org/pdf/1409.3215.pdf)
1. [TensorFlow’s seq2seq Tutorial with Attention (Tutorial on seq2seq+attention)](https://github.com/tensorflow/nmt)
1. [Lilian Weng’s Blog on Attention (Great start to attention)](https://lilianweng.github.io/lil-log/2018/06/24/attention-attention.html#a-family-of-attention-mechanisms)
1. [Jay Alammar’s Blog on Seq2Seq with Attention (Great illustrations and worked example on seq2seq+attention)](https://jalammar.github.io/visualizing-neural-machine-translation-mechanics-of-seq2seq-models-with-attention/)
1. [Google’s Neural Machine Translation System: Bridging the Gap between Human and Machine Translation (Wu et. al, 2016)](https://arxiv.org/pdf/1609.08144.pdf)
1. [Adam: A method for stochastic optimization](https://arxiv.org/pdf/1412.6980.pdf)
1. [BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding](https://arxiv.org/pdf/1810.04805.pdf)

## <span style="color:blue">Contenido</span>

* [Introducción](#Introducción)
* [Creación-de-un-Transformer](#Creación-de-un-Transformer)

## <span style="color:blue">Introducción</span>

En esta lección hacemos un acercamiento a la creación y uso de un modelo transformer en HuggingFace. Usaremos la clase *TFAutoModel* en Tensoflow, *AutoModel* en Torch.

*TFAutoModel* y clases cercanas son envoltorios (wrappers) de una gran variedad de modelos disponibles en la librería transformers.

## <span style="color:blue">Creación de un Transformer</span>

Primero inicializaremos un modelo BERT, cargandolo desde su archivo de configuración.

Para correr el cuaderno original  de HuggingFace para Tensorflow en Colab vaya a  [Huggingface notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/master/course/chapter2/section3_tf.ipynb). Para Torch [aquí](https://colab.research.google.com/github/huggingface/notebooks/blob/master/course/chapter2/section3_pt.ipynb).

In [1]:
from transformers import BertConfig, TFBertModel

# Instancia configuración
config = BertConfig()

# Instancia el modelo desde la configuración
model = TFBertModel(config)

# El modelo fue inicializado aleatoriamente por defecto##

In [2]:
print(config)

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.8.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



El modelo está listo para ser entrenado para una tarea específica. Sin embargo esto requiere tiempo dinero posiblemente y una gran cantidad de datos. Por estas razones, lo razonable actualmente es empezar con un modelo preentrenado.

### Carga de un modelo preentrado

In [ ]:
from transformers import TFBertModel

model = TFBertModel.from_pretrained('bert-base-cased')

Aquí el uso de *TFBertModel* es equivalente a *TFAutoModel*. Para los detalles del modelo entrenado revise su [model card](https://huggingface.co/bert-base-cased). Este modelo fue inicializado con los pesos del checkpoint de pesos actualmente disponible en la fuente (Hugging Face). Ya se puede usar para inferencia en tareas para las cuales fue entrenado. en este caso predecir palabras o sentencias enmascaradas. Para una tarea diferente se puede hacer un ajuste fino (*fine tunning*) que reentrena el modelo con muy pocos pasos.

Los pesos fueron cargados y colocados en una carpeta caché. que por defecto es ~/.cache/huggingface/transformers. Se puede modificar eata direccción de cache con la variable ambiente **HF_HOME**. La lista completa de checkpoints disponibles para BERT se encuentra [aquí](https://huggingface.co/models?filter=bert).

### Métodos para guardar modelos preentrenados.

Se usa el método **save_pretrained**, el cual es análogo al métdos **from_pretrained**

Se almacena dos archivos en el disco:

El archivo *config.json* contiene la configuración del modelo preentrenado en formato json. El archivo *tf_model.h5* es conocido como diccionario de estado (state dictionary) y contiene todos los pesos del modelo para este checkpoint. El formato h5 corresponde a archivos de tipo [hdf5](https://abrirarchivos.info/extension/h5#:~:text=Un%20archivo%20H5%20es%20un,de%20Datos%20Jer%C3%A1rquicos%20(HDF).&text=Los%20archivos%20H5%20se%20usan,instrumentos%20electr%C3%B3nicos%20y%20campos%20m%C3%A9dicos.). Los dos archivos van de la mano. 

### Uso de un modelo Transformer para inferencia

Consideremos el siguiente conjunto de sentencias.

In [4]:
sequences = [
    'Hello',
    'Cool',
    'Nice!'
]

El tokenizer convierte esta secuencias en índices del respectivo vocabulario.

In [5]:
from transformers import AutoTokenizer

checkpoint = 'bert-base-cased'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

#### Tokeniza la secuencia

In [6]:
encoded_secuences = tokenizer(sequences, padding=True, truncation=True, return_tensors='tf') # return ='pt' para tensores pytorch

print(encoded_secuences.input_ids.numpy())

[[  101  8667   102     0]
 [  101 13297   102     0]
 [  101  8835   106   102]]


In [7]:
encoded_secuences = encoded_secuences.input_ids.numpy()

Esta es una lista de secuencias codificadas. Si vamos a comenzar nuestro trabajo con estas secuencias codificadas, las convertimos en tensores

In [8]:
import tensorflow as tf

model_inputs = tf.constant(encoded_secuences)

### Uso de los tensores como entradas al modelo

In [9]:
output = model(model_inputs)
print(output)

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(3, 4, 768), dtype=float32, numpy=
array([[[-0.90261275,  0.46482232, -1.0680807 , ..., -0.699818  ,
          0.0272803 ,  0.8792781 ],
        [-0.2942962 ,  0.43228415, -0.28740913, ...,  0.3589468 ,
         -1.4553845 , -0.7646338 ],
        [ 0.6877541 ,  0.7636266 , -0.20870464, ...,  0.9895973 ,
         -0.38200825,  0.54974   ],
        [ 0.07113194,  0.6081523 , -0.17413221, ...,  0.5636239 ,
         -0.80637443,  0.35920945]],

       [[-0.9534947 ,  0.51484615, -0.96658885, ..., -0.759168  ,
          0.02149527,  0.84670496],
        [ 0.20863365,  1.0134907 , -0.2225053 , ...,  0.81137526,
         -0.75574476, -0.21008678],
        [ 0.6778561 ,  0.77220726,  0.02414589, ...,  1.0647261 ,
         -0.39467815,  0.5474687 ],
        [ 0.05586064,  0.6965945 , -0.03238491, ...,  0.5867801 ,
         -0.73757684,  0.2639028 ]],

       [[-0.3660255 ,  0.6517344 , -1.5038463 , ..., -0.7160782 ,
          0.15

In [10]:
help(output)

Help on TFBaseModelOutputWithPooling in module transformers.modeling_tf_outputs object:

class TFBaseModelOutputWithPooling(transformers.file_utils.ModelOutput)
 |  TFBaseModelOutputWithPooling(last_hidden_state: tensorflow.python.framework.ops.Tensor = None, pooler_output: tensorflow.python.framework.ops.Tensor = None, hidden_states: Union[Tuple[tensorflow.python.framework.ops.Tensor], NoneType] = None, attentions: Union[Tuple[tensorflow.python.framework.ops.Tensor], NoneType] = None) -> None
 |  
 |  Base class for model's outputs that also contains a pooling of the last hidden states.
 |  
 |  Args:
 |      last_hidden_state (:obj:`tf.Tensor` of shape :obj:`(batch_size, sequence_length, hidden_size)`):
 |          Sequence of hidden-states at the output of the last layer of the model.
 |      pooler_output (:obj:`tf.Tensor` of shape :obj:`(batch_size, hidden_size)`):
 |          Last layer hidden-state of the first token of the sequence (classification token) further processed by a
